#!/usr/bin/env python3
# LLM-CONTEXT:BEGIN
# FILE: tool/generate_architecture_docs.py
# ROLE: Owns generate architecture docs behavior within the developer-tooling subsystem.
# DOMAIN: developer-tooling
# SECURITY-INVARIANT: Preserve local-first privacy, bounded resource use, and explicit error handling.
# CHANGE-GUARD: Preserve public contracts, bounded inputs, lifecycle cleanup, and fail-closed behavior; run analysis and relevant tests after edits.
# DOCS: See /docs/llm-context-schema.md and the nearest mermaid.md architecture map.
# LLM-CONTEXT:END
"""Generate auditable repository catalogs and per-subsystem Mermaid maps."""

from __future__ import annotations

import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

FOLDERS = [
    Path("lib"), Path("lib/chat"), Path("lib/food"), Path("lib/memory"),
    Path("lib/model"), Path("lib/navigation"), Path("lib/onboarding"),
    Path("lib/performance"), Path("lib/scanner"), Path("lib/security"),
    Path("lib/settings"), Path("lib/theme"), Path("test"), Path("test_archive"),
    Path("docs"), Path("tool"), Path("tools"), Path("native"), Path("assets"),
    Path("android"), Path("ios"), Path("linux"), Path("macos"),
    Path(".github"), Path("naza_one_asset_pack"),
]

EXCLUDED_PARTS = {".git", ".dart_tool", "build"}
BINARY_SUFFIXES = {".png", ".ttf", ".so", ".dat", ".ico", ".profraw"}


def safe_id(value: str) -> str:
    return "N" + "".join(ch if ch.isalnum() else "_" for ch in value)


def classify(path: Path) -> str:
    rel = path.relative_to(ROOT)
    if any(p in {"ephemeral", ".idea"} for p in rel.parts): return "generated"
    if path.suffix in BINARY_SUFFIXES: return "binary/asset"
    if "generated" in path.name.lower() or path.name in {"pubspec.lock", ".flutter-plugins-dependencies"}: return "generated"
    if path.suffix in {".svg", ".xml", ".plist", ".storyboard", ".xib", ".json"}: return "declarative/resource"
    if path.suffix in {".dart", ".py", ".ps1", ".sh", ".cpp", ".cc", ".h", ".swift", ".kt", ".kts", ".java"}: return "maintained source"
    if path.suffix in {".md", ".txt"}: return "documentation/license"
    return "configuration/other"


def purpose(path: Path) -> str:
    name = path.stem.replace("_", " ").replace("-", " ")
    category = classify(path)
    if category == "binary/asset": return f"Runtime or presentation asset: {name}."
    if category == "generated": return "Tool-generated integration state; regenerate from its owning toolchain instead of hand editing."
    if path.suffix == ".dart": return f"Dart implementation or verification surface for {name}."
    if path.suffix in {".md", ".txt"}: return f"Human-readable guidance or attribution for {name}."
    return f"{category.title()} surface for {name}."


def direct_files(folder: Path) -> list[Path]:
    absolute = ROOT / folder
    if not absolute.exists(): return []
    return sorted(p for p in absolute.iterdir() if p.is_file() and p.name != "mermaid.md")


def direct_dirs(folder: Path) -> list[Path]:
    absolute = ROOT / folder
    if not absolute.exists(): return []
    return sorted(p for p in absolute.iterdir() if p.is_dir() and p.name not in EXCLUDED_PARTS)


def write_map(folder: Path) -> None:
    absolute = ROOT / folder
    if not absolute.exists(): return
    files, dirs = direct_files(folder), direct_dirs(folder)
    title = "/" if str(folder) == "." else folder.as_posix()
    lines = [
        f"# Architecture Map: `{title}`", "",
        "This map is generated by `tool/generate_architecture_docs.py`. It is a navigation aid; executable code and security policy remain authoritative.", "",
        "```mermaid", "flowchart LR", f"    ROOT[\"{title}\"]", "",
    ]
    for directory in dirs:
        rel = directory.relative_to(ROOT).as_posix()
        lines.append(f"    ROOT --> {safe_id(rel)}[\"📁 {directory.name}\"]")
    for file in files:
        rel = file.relative_to(ROOT).as_posix()
        lines.append(f"    ROOT --> {safe_id(rel)}[\"{file.name}\"]")
        lines.append(f"    {safe_id(rel)} -. \"{classify(file)}\" .-> CONTRACT[\"Preserve contracts + invariants\"]")
    if not files and not dirs: lines.append('    ROOT --> EMPTY["No maintained children"]')
    lines.extend(["```", "", "## Files", ""])
    if files:
        lines.extend(["| File | Classification | Purpose |", "|---|---|---|"])
        for file in files:
            rel = file.relative_to(ROOT).as_posix()
            link = os.path.relpath(file, absolute).replace(os.sep, "/")
            lines.append(f"| [`{file.name}`]({link}#L1) | {classify(file)} | {purpose(file)} |")
    else:
        lines.append("No direct files; see child folder maps.")
    lines.extend(["", "## Change protocol", "", "1. Read the file breadcrumb and `SECURITY.md`.", "2. Trace callers, persistence, and async ownership.", "3. Preserve bounds and fail-closed behavior.", "4. Run analysis and focused tests.", ""])
    (absolute / "mermaid.md").write_text("\n".join(lines), encoding="utf-8")


def write_catalog() -> None:
    rows = []
    for path in sorted(ROOT.rglob("*")):
        if not path.is_file() or any(part in EXCLUDED_PARTS for part in path.relative_to(ROOT).parts): continue
        rel = path.relative_to(ROOT).as_posix()
        rows.append((rel, classify(path), purpose(path)))
    lines = [
        "# Repository File Catalog", "",
        "Every tracked or workspace-visible file is classified here. Generated and binary files are intentionally documented without source-comment injection.", "",
        "| Path | Classification | Responsibility / handling |", "|---|---|---|",
    ]
    for rel, category, why in rows:
        lines.append(f"| `{rel}` | {category} | {why} |")
    lines.append("")
    (ROOT / "docs/file-catalog.md").write_text("\n".join(lines), encoding="utf-8")


def write_folder_catalog() -> None:
    mapped = [folder for folder in FOLDERS if (ROOT / folder / "mermaid.md").exists()]
    lines = [
        "# Repository Folder Catalog", "",
        "Every folder is assigned to its nearest safe Mermaid architecture map. Platform resource, generated, and binary-only folders are represented here rather than receiving files that could break their toolchain contract.", "",
        "| Folder | Nearest architecture map | Handling |", "|---|---|---|",
    ]
    for directory in sorted(path for path in ROOT.rglob("*") if path.is_dir() and ".git" not in path.parts and ".dart_tool" not in path.parts and "build" not in path.parts):
        rel = directory.relative_to(ROOT)
        owner = next((folder for folder in sorted(mapped, key=lambda value: len(value.parts), reverse=True) if rel == folder or folder in rel.parents), Path("docs"))
        handling = "Generated/tool-owned: document and regenerate; do not inject comments." if any(part in {"ephemeral", ".idea"} for part in rel.parts) else "Covered by maintained parent architecture map."
        lines.append(f"| `{rel.as_posix()}` | [`{owner.as_posix()}`](../{owner.as_posix()}/mermaid.md) | {handling} |")
    lines.append("")
    (ROOT / "docs/folder-catalog.md").write_text("\n".join(lines), encoding="utf-8")


def write_index() -> None:
    lines = ["# Mermaid Architecture Index", "", "Each maintained subsystem has a local map:", ""]
    for folder in FOLDERS:
        if (ROOT / folder / "mermaid.md").exists():
            lines.append(f"- [`{folder.as_posix()}`](../{folder.as_posix()}/mermaid.md)")
    lines.extend(["", "## Repository-wide flow", "", "```mermaid", "flowchart TD", "    Platform[Platform shells] --> App[lib/app.dart]", "    App --> Navigation[Unified feature registry]", "    Navigation --> Features[Chat · scanners · food · health · intelligence]", "    Features --> Runtime[Local model runtime]", "    Features --> Vault[Encrypted local storage]", "    Runtime --> VerifiedModel[Hash-verified model artifact]", "    Vault --> Security[Security kernel + recovery controls]", "    Tests[Tests] -. verify .-> App", "    Tests -. verify .-> Security", "```", ""])
    (ROOT / "docs/mermaid-index.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    for folder in FOLDERS: write_map(folder)
    write_catalog()
    write_folder_catalog()
    write_index()
    print(f"Generated {sum((ROOT / f / 'mermaid.md').exists() for f in FOLDERS)} folder maps and the repository catalog.")


if __name__ == "__main__": main()
