[CmdletBinding()]
param(
  [string]$LiteRtLmRepo = 'https://github.com/ornab74/LiteRT-LM.git',
  [string]$LiteRtLmRef = '6eeeb1d1195ee83f00e96da82ba1ed63e328063a',
  [string]$LiteRtRef = 'b0f6c12088df229f6342f1af164caa66ffa7b010',
  [switch]$SkipNativeBuild
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

if (-not $IsWindows) {
  throw 'This script builds NAZA One''s Windows LiteRT-LM runtime and must run on Windows.'
}

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
Set-Location $repoRoot

$bridgeVersion = '1.3.1'
$expectedLiteRtLmVersion = '0.16.0'
$localPackageDir = Join-Path $repoRoot '.dart_tool\naza_windows_litertlm_1_3_1'
$sourceRoot = Join-Path $repoRoot '.dart_tool\naza_litertlm_0_16_src'
$liteRtRoot = Join-Path $repoRoot '.dart_tool\naza_litert_src'
$bundleRoot = Join-Path $repoRoot '.dart_tool\naza_windows_modern_bundle'
$overrideFile = Join-Path $repoRoot 'pubspec_overrides.yaml'
$packageConfig = Join-Path $repoRoot '.dart_tool\package_config.json'
$markerFile = Join-Path $repoRoot '.dart_tool\naza_windows_litertlm_provenance.json'
$generatedOverrideHeader = '# GENERATED by tool/prepare_windows_litertlm.ps1 - Windows only'

function Require-Command([string]$Name) {
  $cmd = Get-Command $Name -ErrorAction SilentlyContinue
  if (-not $cmd) { throw "Required command '$Name' was not found in PATH." }
  return $cmd.Source
}

function Invoke-Checked([string]$Exe, [string[]]$Args, [string]$WorkingDirectory = $repoRoot) {
  Write-Host "> $Exe $($Args -join ' ')" -ForegroundColor Cyan
  Push-Location $WorkingDirectory
  try {
    & $Exe @Args
    if ($LASTEXITCODE -ne 0) {
      throw "Command failed with exit code ${LASTEXITCODE}: $Exe $($Args -join ' ')"
    }
  } finally {
    Pop-Location
  }
}

function Resolve-BazelDll([string]$Bazel, [string[]]$CommonArgs, [string]$Target, [string]$WorkingDirectory) {
  Push-Location $WorkingDirectory
  try {
    $lines = & $Bazel cquery @CommonArgs $Target '--output=files'
    if ($LASTEXITCODE -ne 0) { throw "bazel cquery failed for $Target" }
  } finally {
    Pop-Location
  }
  $candidate = $lines | Where-Object { $_ -and $_.Trim().ToLowerInvariant().EndsWith('.dll') } | Select-Object -First 1
  if (-not $candidate) { throw "Could not resolve DLL output for $Target. Output: $($lines -join '; ')" }
  if ([IO.Path]::IsPathRooted($candidate)) { return (Resolve-Path $candidate).Path }
  return (Resolve-Path (Join-Path $WorkingDirectory $candidate)).Path
}

function Assert-NotLfsPointer([string]$Path) {
  if (-not (Test-Path $Path)) { throw "Required runtime file is missing: $Path" }
  $firstLine = Get-Content $Path -TotalCount 1 -ErrorAction Stop
  if ($firstLine -eq 'version https://git-lfs.github.com/spec/v1') {
    throw "Git LFS file is still a pointer: $Path"
  }
}

function Ensure-DetachedCheckout([string]$Git, [string]$Url, [string]$Ref, [string]$Directory) {
  if (-not (Test-Path (Join-Path $Directory '.git'))) {
    if (Test-Path $Directory) { Remove-Item $Directory -Recurse -Force }
    Invoke-Checked $Git @('clone', '--filter=blob:none', '--no-checkout', $Url, $Directory) $repoRoot
  }
  Invoke-Checked $Git @('fetch', '--depth=1', 'origin', $Ref) $Directory
  Invoke-Checked $Git @('checkout', '--detach', $Ref) $Directory
  Invoke-Checked $Git @('reset', '--hard', $Ref) $Directory
}

$Git = Require-Command 'git'
$Flutter = Require-Command 'flutter'

Write-Host '=== NAZA One modern Windows LiteRT-LM preparation ===' -ForegroundColor Green
Write-Host "Dart bridge       : flutter_gemma_litertlm $bridgeVersion"
Write-Host "LiteRT-LM source  : $LiteRtLmRepo @ $LiteRtLmRef"
Write-Host "Expected dev line : $expectedLiteRtLmVersion"
Write-Host "LiteRT source     : google-ai-edge/LiteRT @ $LiteRtRef"
Write-Host 'GPU mitigation    : serialize Windows WebGPU weight upload; GPU compute remains enabled'
Write-Host 'MTP cache policy  : :nocache (Windows project-local bridge only)'

if (Test-Path $overrideFile) {
  $existingOverride = Get-Content $overrideFile -Raw
  if ($existingOverride.StartsWith($generatedOverrideHeader)) {
    Remove-Item $overrideFile -Force
  } elseif ($existingOverride -match 'naza_windows_litertlm') {
    Remove-Item $overrideFile -Force
  } else {
    throw "pubspec_overrides.yaml already exists and was not generated by NAZA tooling: $overrideFile"
  }
}

Invoke-Checked $Flutter @('pub', 'get')
if (-not (Test-Path $packageConfig)) { throw '.dart_tool/package_config.json was not generated.' }
$config = Get-Content $packageConfig -Raw | ConvertFrom-Json
$entry = $config.packages | Where-Object { $_.name -eq 'flutter_gemma_litertlm' } | Select-Object -First 1
if (-not $entry) { throw 'flutter_gemma_litertlm is missing from package_config.json.' }
$rootUri = [Uri]$entry.rootUri
if (-not $rootUri.IsAbsoluteUri) {
  $configUri = [Uri](Resolve-Path $packageConfig).Path
  $rootUri = [Uri]::new($configUri, $rootUri)
}
$sourcePackageDir = $rootUri.LocalPath
$sourcePubspec = Get-Content (Join-Path $sourcePackageDir 'pubspec.yaml') -Raw
if ($sourcePubspec -notmatch '(?m)^version:\s*1\.3\.1\s*$') {
  throw "Expected flutter_gemma_litertlm $bridgeVersion before Windows preparation."
}

Remove-Item $localPackageDir -Recurse -Force -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Force -Path $localPackageDir | Out-Null
Copy-Item (Join-Path $sourcePackageDir '*') $localPackageDir -Recurse -Force

$enginePath = Join-Path $localPackageDir 'lib\src\litert_lm_engine.dart'
$engineText = Get-Content $enginePath -Raw
$cacheNeedle = 'final cacheDir = (await getApplicationSupportDirectory()).path;'
$cacheReplacement = "final cacheDir = ':nocache'; // NAZA Windows: avoid Gemma 4 MTP cache collision (#2572)"
if ($engineText.Contains($cacheNeedle)) {
  $engineText = $engineText.Replace($cacheNeedle, $cacheReplacement)
  Set-Content $enginePath $engineText -Encoding utf8
} elseif ($engineText -notmatch "cacheDir = ':nocache'") {
  throw 'Modern bridge cacheDir source shape changed; refusing a blind patch.'
}

@"
$generatedOverrideHeader
dependency_overrides:
  flutter_gemma_litertlm:
    path: .dart_tool/naza_windows_litertlm_1_3_1
"@ | Set-Content $overrideFile -Encoding utf8
Invoke-Checked $Flutter @('pub', 'get')

$localPubspec = Get-Content (Join-Path $localPackageDir 'pubspec.yaml') -Raw
$hookPath = Join-Path $localPackageDir 'hook\build.dart'
$hookText = Get-Content $hookPath -Raw
if ($localPubspec -notmatch '(?m)^version:\s*1\.3\.1\s*$') { throw 'Local Windows bridge is not 1.3.1.' }
if ($hookText -notmatch "version:\s*'0\.14\.0'") {
  throw 'flutter_gemma_litertlm 1.3.1 native hook no longer declares the expected modern 0.14.0 baseline.'
}

if ($SkipNativeBuild) {
  Write-Host 'Skipping native source build by request.' -ForegroundColor Yellow
  exit 0
}

$BazelCommand = Get-Command 'bazelisk' -ErrorAction SilentlyContinue
if (-not $BazelCommand) { $BazelCommand = Get-Command 'bazel' -ErrorAction SilentlyContinue }
if (-not $BazelCommand) {
  throw 'Bazelisk/Bazel is required. Recommended on Windows: winget install --id=Bazel.Bazelisk -e'
}
$Bazel = $BazelCommand.Source

Ensure-DetachedCheckout $Git $LiteRtLmRepo $LiteRtLmRef $sourceRoot
Invoke-Checked $Git @('lfs', 'install', '--local') $sourceRoot
Invoke-Checked $Git @('lfs', 'pull', '--include=prebuilt/windows_x86_64/*') $sourceRoot

$versionText = Get-Content (Join-Path $sourceRoot 'version.bzl') -Raw
if ($versionText -notmatch 'VERSION\s*=\s*"0\.16\.0"') {
  throw "Pinned LiteRT-LM source is no longer the expected $expectedLiteRtLmVersion development line."
}
$workspaceText = Get-Content (Join-Path $sourceRoot 'WORKSPACE') -Raw
if ($workspaceText -notmatch [regex]::Escape("LITERT_REF = `"$LiteRtRef`"")) {
  throw 'LiteRT-LM WORKSPACE LiteRT pin does not match the NAZA provenance pin.'
}

$patchPath = Join-Path $sourceRoot 'PATCH.litert_windows_nvidia_webgpu_upload'
if (-not (Test-Path $patchPath)) { throw "Windows WebGPU patch is missing: $patchPath" }

Ensure-DetachedCheckout $Git 'https://github.com/google-ai-edge/LiteRT.git' $LiteRtRef $liteRtRoot
Invoke-Checked $Git @('clean', '-fdx') $liteRtRoot
Invoke-Checked $Git @('reset', '--hard', $LiteRtRef) $liteRtRoot
Invoke-Checked $Git @('apply', '--check', $patchPath) $liteRtRoot
Invoke-Checked $Git @('apply', $patchPath) $liteRtRoot

$override = $liteRtRoot.Replace('\', '/')
$commonArgs = @(
  '--config=windows',
  '--define=litert_runtime_link_mode=dynamic',
  '--define=resolve_symbols_in_exec=false',
  "--override_repository=litert=$override"
)
$cApiTarget = '//c:litert-lm'
$acceleratorTarget = '@litert//litert/runtime/accelerators/gpu:libLiteRtWebGpuAccelerator'
Invoke-Checked $Bazel (@('build') + $commonArgs + @($cApiTarget, $acceleratorTarget)) $sourceRoot

$cApiDll = Resolve-BazelDll $Bazel $commonArgs $cApiTarget $sourceRoot
$acceleratorDll = Resolve-BazelDll $Bazel $commonArgs $acceleratorTarget $sourceRoot

Remove-Item $bundleRoot -Recurse -Force -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Force -Path $bundleRoot | Out-Null
$prebuiltRoot = Join-Path $sourceRoot 'prebuilt\windows_x86_64'
Get-ChildItem $prebuiltRoot -Filter '*.dll' | ForEach-Object {
  Assert-NotLfsPointer $_.FullName
  Copy-Item $_.FullName $bundleRoot -Force
}

Copy-Item $cApiDll (Join-Path $bundleRoot 'LiteRtLm.dll') -Force
Copy-Item $acceleratorDll (Join-Path $bundleRoot 'libLiteRtWebGpuAccelerator.dll') -Force

$aliases = [ordered]@{
  'libGemmaModelConstraintProvider.dll' = 'GemmaModelConstraintProvider.dll'
  'libLiteRt.dll' = 'LiteRt.dll'
  'libLiteRtTopKWebGpuSampler.dll' = 'LiteRtTopKWebGpuSampler.dll'
  'libLiteRtWebGpuAccelerator.dll' = 'LiteRtWebGpuAccelerator.dll'
  'libwebgpu_dawn.dll' = 'webgpu_dawn.dll'
}
foreach ($pair in $aliases.GetEnumerator()) {
  $src = Join-Path $bundleRoot $pair.Key
  if (Test-Path $src) { Copy-Item $src (Join-Path $bundleRoot $pair.Value) -Force }
}

$acceleratorOut = Join-Path $bundleRoot 'libLiteRtWebGpuAccelerator.dll'
$cApiOut = Join-Path $bundleRoot 'LiteRtLm.dll'
Assert-NotLfsPointer $acceleratorOut
Assert-NotLfsPointer $cApiOut

$hashes = [ordered]@{}
Get-ChildItem $bundleRoot -Filter '*.dll' | Sort-Object Name | ForEach-Object {
  $hashes[$_.Name] = (Get-FileHash $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
}

$marker = [ordered]@{
  schema = 'naza-windows-litertlm-modern-v1'
  flutter_gemma_litertlm = $bridgeVersion
  flutter_native_baseline = '0.14.0'
  litert_lm_source_version = $expectedLiteRtLmVersion
  litert_lm_repo = $LiteRtLmRepo
  litert_lm_ref = $LiteRtLmRef
  litert_ref = $LiteRtRef
  litert_c_api_version = '0.1.0'
  windows_webgpu_weight_upload = 'serialized'
  windows_gpu_compute = 'enabled'
  windows_gpu_cache = ':nocache'
  c_api_target = $cApiTarget
  accelerator_target = $acceleratorTarget
  c_api_sha256 = $hashes['LiteRtLm.dll']
  accelerator_sha256 = $hashes['libLiteRtWebGpuAccelerator.dll']
  dll_sha256 = $hashes
  generated_at_utc = (Get-Date).ToUniversalTime().ToString('o')
}
$marker | ConvertTo-Json -Depth 8 | Set-Content $markerFile -Encoding utf8

Write-Host ''
Write-Host 'Modern Windows LiteRT-LM bundle is ready.' -ForegroundColor Green
Write-Host "  LiteRT-LM : $expectedLiteRtLmVersion @ $LiteRtLmRef"
Write-Host "  LiteRT    : $LiteRtRef"
Write-Host "  C API DLL : $cApiOut"
Write-Host "  GPU DLL   : $acceleratorOut"
Write-Host "  Bundle    : $bundleRoot"
Write-Host "  Provenance: $markerFile"
Write-Host ''
Write-Host 'This proves the repaired modern runtime built. A physical NVIDIA GPU test is still required.' -ForegroundColor Yellow
